### ISSUE TITLE
gomidi/cc repo missing

### ISSUE THREAD

**Issue by jmccarthy** [gomidi/mid#3]
When trying to `go get github.com/gomidi/mid`, it correctly reports the absence of the gomidi/cc repo. Is this expected?

Thanks!

**Comment by draeron** [comment]
actually the errors is it can't find the module `gomidi/cc v0.2.0`

```
go: finding github.com/gomidi/cc v0.2.0
go: github.com/gomidi/cc@v0.2.0: unknown revision v0.2.0
go: error loading module requirements
```

**Comment by metakeule** [comment]
When Microsoft bought Github, the repos migrated to Gitlab (gitlab.com/gomidi/...) 'cc', and 'mid' are now part of gitlab.com/gomidi/midi.

I have to update all the docs about the migration.

**Comment by mobildetroit** [comment]
I don't see gomidi/cc on getlab...am I missing something?

**Comment by ankushchadha** [comment]
Is there an ETA? A user tried to download 0.16.0 from https://gocenter.io (public GOPROXY) but the GoCenter's validation failed due to missing dependency github.com/gomidi/cc v0.2.0 - https://search.gocenter.io/github.com~2Fgomidi~2Fmid/info

**Comment by moul** [comment]
For your information, I just made a new project last week, with the gomidi version hosted on gitlab, it's quite a nightmare because the documentation is outdated, but it works! Just be patient and brute force the URLs, the versions etc

-> https://github.com/moul/music-paint -> no trace of "github.com/gomidi*", just "gitlab.com/gomidi*"

**Comment by metakeule** [comment]
@ankushchadha @moul   gitlab.com/gomidi/midi and friends is ready now and the dependency of github.com/gomidi/cc is removed from here.
